name: Docker Pipeline

on:
  push:
    branches:
      - master
  workflow_dispatch:

env:
  IMAGE: githubactions01:v1
  REPO: ${{ secrets.DOCKERHUB_USERNAME }}/githubactions01

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Image
        run: docker build -t ${{ env.IMAGE }} .

      - name: Tag Image
        run: docker tag ${{ env.IMAGE }} ${{ env.REPO }}:latest

      - name: Push Image
        run: docker push ${{ env.REPO }}:latest
