name: Reusable Node.js Build

on:
  workflow_call:
    inputs:
      node_version:
        required: true
        type: string
        description: "The version of Node.js to use"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ inputs.node_version }} # Uses the dynamic input!
      - run: npm install
      - run: npm test
